### ISSUE TITLE
Could not load dynamic library "libcudnn.so.8"

### ISSUE THREAD

**Issue by Yunliang81** [leylabmpi/resmico#26]
Hi Developers,

Thank you very much for your contribution to resmico.

I got an error when I run "resmico evaluate".  Please see the following screenshot. 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/49252749/216779243-036c4843-ec23-4175-8e07-8040215c703a.png">
<img width="952" alt="image" src="https://user-images.githubusercontent.com/49252749/216779463-f120537b-f983-40d5-8cbe-ce0df75005fa.png">

I tried to run "conda install -c nvidia cudnn" to fix this issue, but it didn't work.

Could you please help me figure it out?

Thanks,
Peter

**Comment by nick-youngblut** [comment]
Are you using a machine with an nvidia GPU?

**Comment by Yunliang81** [comment]
Hi Nick,

Thank you for your quick response. I think the server I used has nvidida
GUP, I check GPU info with nvidia-smi command. Please see the following
screenshot.
[image: image.png]

Thanks,
Peter

Nick Youngblut ***@***.***> 于2023年2月5日周日 10:20写道：

**Comment by nick-youngblut** [comment]
Your image wasn't actually uploaded. `conda install -c nvidia cudnn` is a conda issue, and is not specific to `resmico`.  I recommend checking the existing docs on installing `cudnn` and help forums. cuDNN issues are quite common, but there are a lot of docs to help with troubleshooting.

**Comment by Yunliang81** [comment]
Thanks for the suggestion. Today, our technical team lead updated libcudnn.so.7 to libcudnn.so.8. on the server, and it works.
